stages:
  - check

image: docker.io/library/maven:3-eclipse-temurin-19-alpine

verify:
  stage: check
  script:
    - apk update
    - apk add yarn
    - mvn verify

sast:
  stage: check

cache:
  key: $CI_JOB_NAME
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors"

include:
  - template: Security/SAST.gitlab-ci.yml
