FROM gradle:6.1-jdk13

EXPOSE 8080
USER gradle

COPY --chown=gradle:gradle build.gradle gradle.properties settings.gradle /src/

WORKDIR /src
RUN gradle --no-daemon dependencies

COPY --chown=gradle:gradle src /src/src
RUN gradle --no-daemon assemble -PskipWeb -PskipDocker

ENV JAVA_TOOL_OPTIONS "-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact"
#ENV GRADLE_OPTS "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["gradle", "quarkusDev"]
